name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      uses: php-actions/composer@v4
      with:
        command: install
        php_version: 7.4
        composer_version: 2
    - name: Lint
      uses: php-actions/composer@v4
      with:
        command: lint
        php_version: 7.4
        composer_version: 2
